### ISSUE TITLE
Issue with pip install -e .

### ISSUE THREAD

**Issue by phyllispeng123** [Vchitect/FasterCache#14]
Hi, thanks for your great work! I follow the instruction strictly but meet the installation problem in `pip install -e .`. Can you help me with it ?

```
Looking in indexes: https://bytedpypi.byted.org/simple/
Obtaining file:///path_to_folder/FasterCache
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [75 lines of output]
      /tmp/pip-build-env-plhg5uhp/overlay/lib/python3.10/site-packages/setuptools/config/_apply_pyprojecttoml.py:72: _MissingDynamic: `license` defined outside of `pyproject.toml` is ignored.
      !!
      
              ********************************************************************************
              The following seems to be defined outside of `pyproject.toml`:
      
              `license = 'Apache Software License 2.0'`
      
              According to the spec (see the link below), however, setuptools CANNOT
              consider this value unless `license` is listed as `dynamic`.
      
              https://packaging.python.org/en/latest/specifications/pyproject-toml/#declaring-project-metadata-the-project-table
      
              To prevent this problem, you can list `license` under `dynamic` or alternatively
              remove the `[project]` table from your file and rely entirely on other means of
              configuration.
              ********************************************************************************
      
      !!
        _handle_missing_dynamic(dist, project_table)
      /tmp/pip-build-env-plhg5uhp/overlay/lib/python3.10/site-packages/setuptools/config/_apply_pyprojecttoml.py:72: _MissingDynamic: `classifiers` defined outside of `pyproject.toml` is ignored.
      !!
      
              ********************************************************************************
              The following seems to be defined outside of `pyproject.toml`:
      
              `classifiers = ['Programming Language :: Python :: 3', 'License :: OSI Approved :: Apache Software License', 'Environment :: GPU :: NVIDIA CUDA', 'Topic :: Scientific/Engineering :: Artificial Intelligence', 'Topic :: System :: Distributed Computing']`
      
              According to the spec (see the link below), however, setuptools CANNOT
              consider this value unless `classifiers` is listed as `dynamic`.
      
              https://packaging.python.org/en/latest/specifications/pyproject-toml/#declaring-project-metadata-the-project-table
      
              To prevent this problem, you can list `classifiers` under `dynamic` or alternatively
              remove the `[project]` table from your file and rely entirely on other means of
              configuration.
              ********************************************************************************
      
      !!
        _handle_missing_dynamic(dist, project_table)
      /tmp/pip-build-env-plhg5uhp/overlay/lib/python3.10/site-packages/setuptools/config/_apply_pyprojecttoml.py:79: SetuptoolsWarning: `install_requires` overwritten in `pyproject.toml` (dependencies)
        corresp(dist, value, root_dir)
      Traceback (most recent call last):
        File "/my_env/miniconda3/envs/fastercache/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/my_env/miniconda3/envs/fastercache/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/my_env/miniconda3/envs/fastercache/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
        File "/tmp/pip-build-env-plhg5uhp/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 483, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "/tmp/pip-build-env-plhg5uhp/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/tmp/pip-build-env-plhg5uhp/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-plhg5uhp/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-plhg5uhp/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 31, in <module>
        File "/tmp/pip-build-env-plhg5uhp/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-plhg5uhp/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 157, in setup
          dist.parse_config_files()
        File "/tmp/pip-build-env-plhg5uhp/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 648, in parse_config_files
          pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
        File "/tmp/pip-build-env-plhg5uhp/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 73, in apply_configuration
          return _apply(dist, config, filepath)
        File "/tmp/pip-build-env-plhg5uhp/overlay/lib/python3.10/site-packages/setuptools/config/_apply_pyprojecttoml.py", line 53, in apply
          _apply_project_table(dist, config, root_dir)
        File "/tmp/pip-build-env-plhg5uhp/overlay/lib/python3.10/site-packages/setuptools/config/_apply_pyprojecttoml.py", line 79, in _apply_project_table
          corresp(dist, value, root_dir)
        File "/tmp/pip-build-env-plhg5uhp/overlay/lib/python3.10/site-packages/setuptools/config/_apply_pyprojecttoml.py", line 184, in _license
          _set_config(dist, "license", val["text"])
      KeyError: 'text'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by cszy98** [comment]
You could try removing the pyproject.toml file before installation, as it is used for setting up the environment for mochi. Thank you.

**Comment by phyllispeng123** [comment]
> You could try removing the pyproject.toml file before installation, as it is used for setting up the environment for mochi. Thank you.

@cszy98 Thank you, I just delete the pyproject and it works. However, as I run bash scripts/cogvideox/fastercache_sample_cogvideox.sh, it seems like it stucks on `init_process_groups`, I wonder how to solve it? many thanks!!

**Comment by cszy98** [comment]
Have you downloaded the model files correctly? We followed the model files downloaded from this source: https://github.com/THUDM/CogVideo/tree/8ddc8c17d977738060839297000146b04d20350c/sat

**Comment by phyllispeng123** [comment]
> Have you downloaded the model files correctly? We followed the model files downloaded from this source: https://github.com/THUDM/CogVideo/tree/8ddc8c17d977738060839297000146b04d20350c/sat
<img width="306" alt="截屏2024-12-31 17 28 48" src="https://github.com/user-attachments/assets/9bb481ef-1c2c-4a0f-8a4b-55bb1a18ee05" />

Thanks for your reminder, I just dowload the model weights, then run again, I still stuck on `init_process_groups`

**Comment by haochengxi** [comment]
You should change python to torchrun --standalone in the running script
